# Generated by CMake, DO NOT EDIT
/Users/johnty/Documents/yarp-2.3.22_iOS/CMakeFiles/cmake.check_cache: \
/Users/johnty/Documents/yarp-2.3.22_iOS/src/libYARP_OS/CMakeLists.txt
	/opt/local/bin/cmake -H/Users/johnty/Documents/yarp-2.3.22_iOS -B/Users/johnty/Documents/yarp-2.3.22_iOS
